# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 799)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 651, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.current_sensor = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_sensor.setFont(font)
        self.current_sensor.setAlignment(QtCore.Qt.AlignCenter)
        self.current_sensor.setObjectName("current_sensor")
        self.horizontalLayout.addWidget(self.current_sensor)
        self.c_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.c_value.setFont(font)
        self.c_value.setObjectName("c_value")
        self.horizontalLayout.addWidget(self.c_value)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.current_sensor_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_sensor_3.setFont(font)
        self.current_sensor_3.setAlignment(QtCore.Qt.AlignCenter)
        self.current_sensor_3.setObjectName("current_sensor_3")
        self.horizontalLayout_3.addWidget(self.current_sensor_3)
        self.e_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.e_value.setFont(font)
        self.e_value.setObjectName("e_value")
        self.horizontalLayout_3.addWidget(self.e_value)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.current_sensor_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_sensor_2.setFont(font)
        self.current_sensor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.current_sensor_2.setObjectName("current_sensor_2")
        self.horizontalLayout_2.addWidget(self.current_sensor_2)
        self.c_situation = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.c_situation.setFont(font)
        self.c_situation.setObjectName("c_situation")
        self.horizontalLayout_2.addWidget(self.c_situation)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.verticalLayout.addWidget(self.button_start)
        self.button_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_stop.setFont(font)
        self.button_stop.setObjectName("button_stop")
        self.verticalLayout.addWidget(self.button_stop)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.current_sensor.setText(_translate("MainWindow", "Current Sensor Value : "))
        self.c_value.setText(_translate("MainWindow", "TextLabel"))
        self.current_sensor_3.setText(_translate("MainWindow", "Estimated Sensor Value : "))
        self.e_value.setText(_translate("MainWindow", "TextLabel"))
        self.current_sensor_2.setText(_translate("MainWindow", "Current Situation : "))
        self.c_situation.setText(_translate("MainWindow", "TextLabel"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_stop.setText(_translate("MainWindow", "Stop"))

